### ISSUE TITLE
Who owns what method?

### ISSUE THREAD

**Issue by ben18785** [pints-team/method-merge-tests#1]
# Non-gradient
- [x] Differential evolution: done #9
- [ ] DRAM: @ben18785 ? Very old PR #35 
- [x] DREAM: done #10
- [x] Emcee hammer: done #12
- [x] Haario AC: done #6
- [x] Haario-Bardenet AC: done #6
- [ ] Metropolis: PR by @chonlei - changes requested #17
- [x] Population: done #23
- [ ] Rao-Blackwell AC: @Rebecca-Rumney 
- [x] Slice doubling: done #31
- [ ] Slice stepout: PR by @FarmHJ #27

# Gradient
- [ ] HMC: PR by @FarmHJ #39 
- [ ] MALA: PR by @fcooper8472 #25
- [x] NUTS: @I-Bouros #29 
- [x] Monomial gamma HMC: done #12
- [x] Relativistic HMC: done #21
- [ ] Slice rank shrinking:

# Nested
- [ ] Ellipsoid
- [ ] Rejection

# ABC - not for paper
- [ ] rejection
- [ ] smc

# Stochastic optimisers
- [x] CMAES: done #24
- [x] CMAES bare bones implementation: done #24
- [ ] PSO
- [x] SNES: done #34 
- [ ] XNES: PR by @MichaelClerx in #33 

# Deterministic optimisers - not for paper
- Ee do a notebook, but no statistical tests. Instead, write good value-based unit tests: start from a known position, check that you take the correct step.
- [ ] Adam
- [x] Gradient descent done #37 
- [ ] irpropmin
- [ ] Nelder-mead

**Comment by MichaelClerx** [comment]
Don't forget the optimisers

**Comment by ben18785** [comment]
You're right: you own those :)

- optimisers @MichaelClerx 

(I was thinking we'd cross that bridge after we'd got the samplers sorted?)

**Comment by martinjrobins** [comment]
stupid question, how do you run the existing notebooks, I'm running the hario bardenet one and get the error:

```
ModuleNotFoundError: No module named 'pints.functionaltests'
```

were are `pints.functionaltests` located?

**Comment by MichaelClerx** [comment]
You need this branch: https://github.com/pints-team/pints/pull/1295

**Comment by fcooper8472** [comment]
They are currently in a branch: https://github.com/pints-team/pints/pull/1295
